# GitHub Action for Zend Framework
name: Testing Zend Framework
on: [push, pull_request]
jobs:
  build:
    strategy:
      max-parallel: 6
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        php-versions: ['7.2', '7.3']
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@master #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: mbstring, bcmath, curl, intl
          coverage: xdebug #optional
      - name: Install dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
          composer require --dev phpunit/phpunit squizlabs/php_codesniffer zendframework/zend-test
      - name: Test with phpunit
        run: vendor/bin/phpunit --coverage-text
        shell: pwsh